-- Reference data supplied for the PokéData type recommendation system.
insert into public.types (code, name_pt, sort_order)
values
  ('normal', 'Normal', 1),
  ('fire', 'Fogo', 2),
  ('water', 'Água', 3),
  ('electric', 'Elétrico', 4),
  ('grass', 'Planta', 5),
  ('ice', 'Gelo', 6),
  ('fighting', 'Lutador', 7),
  ('poison', 'Veneno', 8),
  ('ground', 'Terra', 9),
  ('flying', 'Voador', 10),
  ('psychic', 'Psíquico', 11),
  ('bug', 'Inseto', 12),
  ('rock', 'Pedra', 13),
  ('ghost', 'Fantasma', 14),
  ('dragon', 'Dragão', 15),
  ('dark', 'Sombrio', 16),
  ('steel', 'Aço', 17),
  ('fairy', 'Fada', 18);

insert into public.community_species_types (species, type_code, slot)
values
  ('Bulbasaur', 'grass', 1),
  ('Bulbasaur', 'poison', 2),
  ('Ivysaur', 'grass', 1),
  ('Ivysaur', 'poison', 2),
  ('Venusaur', 'grass', 1),
  ('Venusaur', 'poison', 2),
  ('Charmander', 'fire', 1),
  ('Charmeleon', 'fire', 1),
  ('Charizard', 'fire', 1),
  ('Charizard', 'flying', 2),
  ('Squirtle', 'water', 1),
  ('Wartortle', 'water', 1),
  ('Blastoise', 'water', 1),
  ('Caterpie', 'bug', 1),
  ('Metapod', 'bug', 1),
  ('Butterfree', 'bug', 1),
  ('Butterfree', 'flying', 2),
  ('Weedle', 'bug', 1),
  ('Weedle', 'poison', 2),
  ('Kakuna', 'bug', 1),
  ('Kakuna', 'poison', 2),
  ('Beedrill', 'bug', 1),
  ('Beedrill', 'poison', 2),
  ('Pidgey', 'normal', 1),
  ('Pidgey', 'flying', 2),
  ('Pidgeotto', 'normal', 1),
  ('Pidgeotto', 'flying', 2),
  ('Pidgeot', 'normal', 1),
  ('Pidgeot', 'flying', 2),
  ('Rattata', 'normal', 1),
  ('Raticate', 'normal', 1),
  ('Spearow', 'normal', 1),
  ('Spearow', 'flying', 2),
  ('Fearow', 'normal', 1),
  ('Fearow', 'flying', 2),
  ('Ekans', 'poison', 1),
  ('Arbok', 'poison', 1),
  ('Pikachu', 'electric', 1),
  ('Raichu', 'electric', 1),
  ('Sandshrew', 'ground', 1),
  ('Sandslash', 'ground', 1),
  ('NidoranF', 'poison', 1),
  ('Nidorina', 'poison', 1),
  ('Nidoqueen', 'poison', 1),
  ('Nidoqueen', 'ground', 2),
  ('NidoranM', 'poison', 1),
  ('Nidorino', 'poison', 1),
  ('Nidoking', 'poison', 1),
  ('Nidoking', 'ground', 2),
  ('Clefairy', 'fairy', 1),
  ('Clefable', 'fairy', 1),
  ('Vulpix', 'fire', 1),
  ('Ninetales', 'fire', 1),
  ('Jigglypuff', 'normal', 1),
  ('Jigglypuff', 'fairy', 2),
  ('Wigglytuff', 'normal', 1),
  ('Wigglytuff', 'fairy', 2),
  ('Zubat', 'poison', 1),
  ('Zubat', 'flying', 2),
  ('Golbat', 'poison', 1),
  ('Golbat', 'flying', 2),
  ('Oddish', 'grass', 1),
  ('Oddish', 'poison', 2),
  ('Gloom', 'grass', 1),
  ('Gloom', 'poison', 2),
  ('Vileplume', 'grass', 1),
  ('Vileplume', 'poison', 2),
  ('Paras', 'bug', 1),
  ('Paras', 'grass', 2),
  ('Parasect', 'bug', 1),
  ('Parasect', 'grass', 2),
  ('Venonat', 'bug', 1),
  ('Venonat', 'poison', 2),
  ('Venomoth', 'bug', 1),
  ('Venomoth', 'poison', 2),
  ('Diglett', 'ground', 1),
  ('Dugtrio', 'ground', 1),
  ('Meowth', 'normal', 1),
  ('Persian', 'normal', 1),
  ('Psyduck', 'water', 1),
  ('Golduck', 'water', 1),
  ('Mankey', 'fighting', 1),
  ('Primeape', 'fighting', 1),
  ('Growlithe', 'fire', 1),
  ('Arcanine', 'fire', 1),
  ('Poliwag', 'water', 1),
  ('Poliwhirl', 'water', 1),
  ('Poliwrath', 'water', 1),
  ('Poliwrath', 'fighting', 2),
  ('Abra', 'psychic', 1),
  ('Kadabra', 'psychic', 1),
  ('Alakazam', 'psychic', 1),
  ('Machop', 'fighting', 1),
  ('Machoke', 'fighting', 1),
  ('Machamp', 'fighting', 1),
  ('Bellsprout', 'grass', 1),
  ('Bellsprout', 'poison', 2),
  ('Weepinbell', 'grass', 1),
  ('Weepinbell', 'poison', 2),
  ('Victreebel', 'grass', 1),
  ('Victreebel', 'poison', 2),
  ('Tentacool', 'water', 1),
  ('Tentacool', 'poison', 2),
  ('Tentacruel', 'water', 1),
  ('Tentacruel', 'poison', 2),
  ('Geodude', 'rock', 1),
  ('Geodude', 'ground', 2),
  ('Graveler', 'rock', 1),
  ('Graveler', 'ground', 2),
  ('Golem', 'rock', 1),
  ('Golem', 'ground', 2),
  ('Ponyta', 'fire', 1),
  ('Rapidash', 'fire', 1),
  ('Slowpoke', 'water', 1),
  ('Slowpoke', 'psychic', 2),
  ('Slowbro', 'water', 1),
  ('Slowbro', 'psychic', 2),
  ('Magnemite', 'electric', 1),
  ('Magnemite', 'steel', 2),
  ('Magneton', 'electric', 1),
  ('Magneton', 'steel', 2),
  ('Farfetchd', 'normal', 1),
  ('Farfetchd', 'flying', 2),
  ('Doduo', 'normal', 1),
  ('Doduo', 'flying', 2),
  ('Dodrio', 'normal', 1),
  ('Dodrio', 'flying', 2),
  ('Seel', 'water', 1),
  ('Dewgong', 'water', 1),
  ('Dewgong', 'ice', 2),
  ('Grimer', 'poison', 1),
  ('Muk', 'poison', 1),
  ('Shellder', 'water', 1),
  ('Cloyster', 'water', 1),
  ('Cloyster', 'ice', 2),
  ('Gastly', 'ghost', 1),
  ('Gastly', 'poison', 2),
  ('Haunter', 'ghost', 1),
  ('Haunter', 'poison', 2),
  ('Gengar', 'ghost', 1),
  ('Gengar', 'poison', 2),
  ('Onix', 'rock', 1),
  ('Onix', 'ground', 2),
  ('Drowzee', 'psychic', 1),
  ('Hypno', 'psychic', 1),
  ('Krabby', 'water', 1),
  ('Kingler', 'water', 1),
  ('Voltorb', 'electric', 1),
  ('Electrode', 'electric', 1),
  ('Exeggcute', 'grass', 1),
  ('Exeggcute', 'psychic', 2),
  ('Exeggutor', 'grass', 1),
  ('Exeggutor', 'psychic', 2),
  ('Cubone', 'ground', 1),
  ('Marowak', 'ground', 1),
  ('Hitmonlee', 'fighting', 1),
  ('Hitmonchan', 'fighting', 1),
  ('Lickitung', 'normal', 1),
  ('Koffing', 'poison', 1),
  ('Weezing', 'poison', 1),
  ('Rhyhorn', 'ground', 1),
  ('Rhyhorn', 'rock', 2),
  ('Rhydon', 'ground', 1),
  ('Rhydon', 'rock', 2),
  ('Chansey', 'normal', 1),
  ('Tangela', 'grass', 1),
  ('Kangaskhan', 'normal', 1),
  ('Horsea', 'water', 1),
  ('Seadra', 'water', 1),
  ('Goldeen', 'water', 1),
  ('Seaking', 'water', 1),
  ('Staryu', 'water', 1),
  ('Starmie', 'water', 1),
  ('Starmie', 'psychic', 2),
  ('MrMime', 'psychic', 1),
  ('MrMime', 'fairy', 2),
  ('Scyther', 'bug', 1),
  ('Scyther', 'flying', 2),
  ('Jynx', 'ice', 1),
  ('Jynx', 'psychic', 2),
  ('Electabuzz', 'electric', 1),
  ('Magmar', 'fire', 1),
  ('Pinsir', 'bug', 1),
  ('Tauros', 'normal', 1),
  ('Magikarp', 'water', 1),
  ('Gyarados', 'water', 1),
  ('Gyarados', 'flying', 2),
  ('Lapras', 'water', 1),
  ('Lapras', 'ice', 2),
  ('Ditto', 'normal', 1),
  ('Eevee', 'normal', 1),
  ('Vaporeon', 'water', 1),
  ('Jolteon', 'electric', 1),
  ('Flareon', 'fire', 1),
  ('Porygon', 'normal', 1),
  ('Omanyte', 'rock', 1),
  ('Omanyte', 'water', 2),
  ('Omastar', 'rock', 1),
  ('Omastar', 'water', 2),
  ('Kabuto', 'rock', 1),
  ('Kabuto', 'water', 2),
  ('Kabutops', 'rock', 1),
  ('Kabutops', 'water', 2),
  ('Aerodactyl', 'rock', 1),
  ('Aerodactyl', 'flying', 2),
  ('Snorlax', 'normal', 1),
  ('Dratini', 'dragon', 1),
  ('Dragonair', 'dragon', 1),
  ('Dragonite', 'dragon', 1),
  ('Dragonite', 'flying', 2),
  ('Chikorita', 'grass', 1),
  ('Bayleef', 'grass', 1),
  ('Meganium', 'grass', 1),
  ('Cyndaquil', 'fire', 1),
  ('Quilava', 'fire', 1),
  ('Typhlosion', 'fire', 1),
  ('Totodile', 'water', 1),
  ('Croconaw', 'water', 1),
  ('Feraligatr', 'water', 1),
  ('Sentret', 'normal', 1),
  ('Furret', 'normal', 1),
  ('Hoothoot', 'normal', 1),
  ('Hoothoot', 'flying', 2),
  ('Noctowl', 'normal', 1),
  ('Noctowl', 'flying', 2),
  ('Ledyba', 'bug', 1),
  ('Ledyba', 'flying', 2),
  ('Ledian', 'bug', 1),
  ('Ledian', 'flying', 2),
  ('Spinarak', 'bug', 1),
  ('Spinarak', 'poison', 2),
  ('Ariados', 'bug', 1),
  ('Ariados', 'poison', 2),
  ('Crobat', 'poison', 1),
  ('Crobat', 'flying', 2),
  ('Chinchou', 'water', 1),
  ('Chinchou', 'electric', 2),
  ('Lanturn', 'water', 1),
  ('Lanturn', 'electric', 2),
  ('Pichu', 'electric', 1),
  ('Cleffa', 'fairy', 1),
  ('Igglybuff', 'normal', 1),
  ('Igglybuff', 'fairy', 2),
  ('Togepi', 'fairy', 1),
  ('Togetic', 'fairy', 1),
  ('Togetic', 'flying', 2),
  ('Natu', 'psychic', 1),
  ('Natu', 'flying', 2),
  ('Xatu', 'psychic', 1),
  ('Xatu', 'flying', 2),
  ('Mareep', 'electric', 1),
  ('Flaaffy', 'electric', 1),
  ('Ampharos', 'electric', 1),
  ('Bellossom', 'grass', 1),
  ('Marill', 'water', 1),
  ('Marill', 'fairy', 2),
  ('Azumarill', 'water', 1),
  ('Azumarill', 'fairy', 2),
  ('Sudowoodo', 'rock', 1),
  ('Politoed', 'water', 1),
  ('Hoppip', 'grass', 1),
  ('Hoppip', 'flying', 2),
  ('Skiploom', 'grass', 1),
  ('Skiploom', 'flying', 2),
  ('Jumpluff', 'grass', 1),
  ('Jumpluff', 'flying', 2),
  ('Aipom', 'normal', 1),
  ('Sunkern', 'grass', 1),
  ('Sunflora', 'grass', 1),
  ('Yanma', 'bug', 1),
  ('Yanma', 'flying', 2),
  ('Wooper', 'water', 1),
  ('Wooper', 'ground', 2),
  ('Quagsire', 'water', 1),
  ('Quagsire', 'ground', 2),
  ('Espeon', 'psychic', 1),
  ('Umbreon', 'dark', 1),
  ('Murkrow', 'dark', 1),
  ('Murkrow', 'flying', 2),
  ('Slowking', 'water', 1),
  ('Slowking', 'psychic', 2),
  ('Misdreavus', 'ghost', 1),
  ('Unown', 'psychic', 1),
  ('Wobbuffet', 'psychic', 1),
  ('Girafarig', 'normal', 1),
  ('Girafarig', 'psychic', 2),
  ('Pineco', 'bug', 1),
  ('Forretress', 'bug', 1),
  ('Forretress', 'steel', 2),
  ('Dunsparce', 'normal', 1),
  ('Gligar', 'ground', 1),
  ('Gligar', 'flying', 2),
  ('Steelix', 'steel', 1),
  ('Steelix', 'ground', 2),
  ('Snubbull', 'fairy', 1),
  ('Granbull', 'fairy', 1),
  ('Qwilfish', 'water', 1),
  ('Qwilfish', 'poison', 2),
  ('Scizor', 'bug', 1),
  ('Scizor', 'steel', 2),
  ('Shuckle', 'bug', 1),
  ('Shuckle', 'rock', 2),
  ('Heracross', 'bug', 1),
  ('Heracross', 'fighting', 2),
  ('Sneasel', 'dark', 1),
  ('Sneasel', 'ice', 2),
  ('Teddiursa', 'normal', 1),
  ('Ursaring', 'normal', 1),
  ('Slugma', 'fire', 1),
  ('Magcargo', 'fire', 1),
  ('Magcargo', 'rock', 2),
  ('Swinub', 'ice', 1),
  ('Swinub', 'ground', 2),
  ('Piloswine', 'ice', 1),
  ('Piloswine', 'ground', 2),
  ('Corsola', 'water', 1),
  ('Corsola', 'rock', 2),
  ('Remoraid', 'water', 1),
  ('Octillery', 'water', 1),
  ('Delibird', 'ice', 1),
  ('Delibird', 'flying', 2),
  ('Mantine', 'water', 1),
  ('Mantine', 'flying', 2),
  ('Skarmory', 'steel', 1),
  ('Skarmory', 'flying', 2),
  ('Houndour', 'dark', 1),
  ('Houndour', 'fire', 2),
  ('Houndoom', 'dark', 1),
  ('Houndoom', 'fire', 2),
  ('Kingdra', 'water', 1),
  ('Kingdra', 'dragon', 2),
  ('Phanpy', 'ground', 1),
  ('Donphan', 'ground', 1),
  ('Porygon2', 'normal', 1),
  ('Stantler', 'normal', 1),
  ('Smeargle', 'normal', 1),
  ('Tyrogue', 'fighting', 1),
  ('Hitmontop', 'fighting', 1),
  ('Smoochum', 'ice', 1),
  ('Smoochum', 'psychic', 2),
  ('Elekid', 'electric', 1),
  ('Magby', 'fire', 1),
  ('Miltank', 'normal', 1),
  ('Blissey', 'normal', 1),
  ('Larvitar', 'rock', 1),
  ('Larvitar', 'ground', 2),
  ('Pupitar', 'rock', 1),
  ('Pupitar', 'ground', 2),
  ('Tyranitar', 'rock', 1),
  ('Tyranitar', 'dark', 2);

update public.community_species as target
set attack_type_code = source.attack_type_code
from (
  values
  ('Bulbasaur', 'grass'),
  ('Ivysaur', 'grass'),
  ('Venusaur', 'grass'),
  ('Charmander', 'fire'),
  ('Charmeleon', 'fire'),
  ('Charizard', 'fire'),
  ('Squirtle', 'water'),
  ('Wartortle', 'water'),
  ('Blastoise', 'water'),
  ('Caterpie', 'bug'),
  ('Metapod', 'bug'),
  ('Butterfree', 'bug'),
  ('Weedle', 'bug'),
  ('Kakuna', 'bug'),
  ('Beedrill', 'bug'),
  ('Pidgey', 'normal'),
  ('Pidgeotto', 'normal'),
  ('Pidgeot', 'normal'),
  ('Rattata', 'normal'),
  ('Raticate', 'normal'),
  ('Spearow', 'normal'),
  ('Fearow', 'normal'),
  ('Ekans', 'poison'),
  ('Arbok', 'poison'),
  ('Pikachu', 'electric'),
  ('Raichu', 'electric'),
  ('Sandshrew', 'ground'),
  ('Sandslash', 'ground'),
  ('NidoranF', 'poison'),
  ('Nidorina', 'poison'),
  ('Nidoqueen', 'poison'),
  ('NidoranM', 'poison'),
  ('Nidorino', 'poison'),
  ('Nidoking', 'poison'),
  ('Clefairy', 'fairy'),
  ('Clefable', 'fairy'),
  ('Vulpix', 'fire'),
  ('Ninetales', 'fire'),
  ('Jigglypuff', 'normal'),
  ('Wigglytuff', 'normal'),
  ('Zubat', 'poison'),
  ('Golbat', 'poison'),
  ('Oddish', 'grass'),
  ('Gloom', 'grass'),
  ('Vileplume', 'grass'),
  ('Paras', 'bug'),
  ('Parasect', 'bug'),
  ('Venonat', 'bug'),
  ('Venomoth', 'bug'),
  ('Diglett', 'ground'),
  ('Dugtrio', 'ground'),
  ('Meowth', 'normal'),
  ('Persian', 'normal'),
  ('Psyduck', 'water'),
  ('Golduck', 'water'),
  ('Mankey', 'fighting'),
  ('Primeape', 'fighting'),
  ('Growlithe', 'fire'),
  ('Arcanine', 'fire'),
  ('Poliwag', 'water'),
  ('Poliwhirl', 'water'),
  ('Poliwrath', 'water'),
  ('Abra', 'psychic'),
  ('Kadabra', 'psychic'),
  ('Alakazam', 'psychic'),
  ('Machop', 'fighting'),
  ('Machoke', 'fighting'),
  ('Machamp', 'fighting'),
  ('Bellsprout', 'grass'),
  ('Weepinbell', 'grass'),
  ('Victreebel', 'grass'),
  ('Tentacool', 'water'),
  ('Tentacruel', 'water'),
  ('Geodude', 'rock'),
  ('Graveler', 'rock'),
  ('Golem', 'rock'),
  ('Ponyta', 'fire'),
  ('Rapidash', 'fire'),
  ('Slowpoke', 'water'),
  ('Slowbro', 'water'),
  ('Magnemite', 'electric'),
  ('Magneton', 'electric'),
  ('Farfetchd', 'normal'),
  ('Doduo', 'normal'),
  ('Dodrio', 'normal'),
  ('Seel', 'water'),
  ('Dewgong', 'water'),
  ('Grimer', 'poison'),
  ('Muk', 'poison'),
  ('Shellder', 'water'),
  ('Cloyster', 'water'),
  ('Gastly', 'ghost'),
  ('Haunter', 'ghost'),
  ('Gengar', 'ghost'),
  ('Onix', 'rock'),
  ('Drowzee', 'psychic'),
  ('Hypno', 'psychic'),
  ('Krabby', 'water'),
  ('Kingler', 'water'),
  ('Voltorb', 'electric'),
  ('Electrode', 'electric'),
  ('Exeggcute', 'grass'),
  ('Exeggutor', 'grass'),
  ('Cubone', 'ground'),
  ('Marowak', 'ground'),
  ('Hitmonlee', 'fighting'),
  ('Hitmonchan', 'fighting'),
  ('Lickitung', 'normal'),
  ('Koffing', 'poison'),
  ('Weezing', 'poison'),
  ('Rhyhorn', 'ground'),
  ('Rhydon', 'ground'),
  ('Chansey', 'normal'),
  ('Tangela', 'grass'),
  ('Kangaskhan', 'normal'),
  ('Horsea', 'water'),
  ('Seadra', 'water'),
  ('Goldeen', 'water'),
  ('Seaking', 'water'),
  ('Staryu', 'water'),
  ('Starmie', 'water'),
  ('MrMime', 'psychic'),
  ('Scyther', 'bug'),
  ('Jynx', 'ice'),
  ('Electabuzz', 'electric'),
  ('Magmar', 'fire'),
  ('Pinsir', 'bug'),
  ('Tauros', 'normal'),
  ('Magikarp', 'water'),
  ('Gyarados', 'water'),
  ('Lapras', 'water'),
  ('Ditto', 'normal'),
  ('Eevee', 'normal'),
  ('Vaporeon', 'water'),
  ('Jolteon', 'electric'),
  ('Flareon', 'fire'),
  ('Porygon', 'normal'),
  ('Omanyte', 'rock'),
  ('Omastar', 'rock'),
  ('Kabuto', 'rock'),
  ('Kabutops', 'rock'),
  ('Aerodactyl', 'rock'),
  ('Snorlax', 'normal'),
  ('Dratini', 'dragon'),
  ('Dragonair', 'dragon'),
  ('Dragonite', 'dragon'),
  ('Chikorita', 'grass'),
  ('Bayleef', 'grass'),
  ('Meganium', 'grass'),
  ('Cyndaquil', 'fire'),
  ('Quilava', 'fire'),
  ('Typhlosion', 'fire'),
  ('Totodile', 'water'),
  ('Croconaw', 'water'),
  ('Feraligatr', 'water'),
  ('Sentret', 'normal'),
  ('Furret', 'normal'),
  ('Hoothoot', 'normal'),
  ('Noctowl', 'normal'),
  ('Ledyba', 'bug'),
  ('Ledian', 'bug'),
  ('Spinarak', 'bug'),
  ('Ariados', 'bug'),
  ('Crobat', 'poison'),
  ('Chinchou', 'water'),
  ('Lanturn', 'water'),
  ('Pichu', 'electric'),
  ('Cleffa', 'fairy'),
  ('Igglybuff', 'normal'),
  ('Togepi', 'fairy'),
  ('Togetic', 'fairy'),
  ('Natu', 'psychic'),
  ('Xatu', 'psychic'),
  ('Mareep', 'electric'),
  ('Flaaffy', 'electric'),
  ('Ampharos', 'electric'),
  ('Bellossom', 'grass'),
  ('Marill', 'water'),
  ('Azumarill', 'water'),
  ('Sudowoodo', 'rock'),
  ('Politoed', 'water'),
  ('Hoppip', 'grass'),
  ('Skiploom', 'grass'),
  ('Jumpluff', 'grass'),
  ('Aipom', 'normal'),
  ('Sunkern', 'grass'),
  ('Sunflora', 'grass'),
  ('Yanma', 'bug'),
  ('Wooper', 'water'),
  ('Quagsire', 'water'),
  ('Espeon', 'psychic'),
  ('Umbreon', 'dark'),
  ('Murkrow', 'dark'),
  ('Slowking', 'water'),
  ('Misdreavus', 'ghost'),
  ('Unown', 'psychic'),
  ('Wobbuffet', 'psychic'),
  ('Girafarig', 'normal'),
  ('Pineco', 'bug'),
  ('Forretress', 'bug'),
  ('Dunsparce', 'normal'),
  ('Gligar', 'ground'),
  ('Steelix', 'steel'),
  ('Snubbull', 'fairy'),
  ('Granbull', 'fairy'),
  ('Qwilfish', 'water'),
  ('Scizor', 'bug'),
  ('Shuckle', 'bug'),
  ('Heracross', 'bug'),
  ('Sneasel', 'dark'),
  ('Teddiursa', 'normal'),
  ('Ursaring', 'normal'),
  ('Slugma', 'fire'),
  ('Magcargo', 'fire'),
  ('Swinub', 'ice'),
  ('Piloswine', 'ice'),
  ('Corsola', 'water'),
  ('Remoraid', 'water'),
  ('Octillery', 'water'),
  ('Delibird', 'ice'),
  ('Mantine', 'water'),
  ('Skarmory', 'steel'),
  ('Houndour', 'dark'),
  ('Houndoom', 'dark'),
  ('Kingdra', 'water'),
  ('Phanpy', 'ground'),
  ('Donphan', 'ground'),
  ('Porygon2', 'normal'),
  ('Stantler', 'normal'),
  ('Smeargle', 'normal'),
  ('Tyrogue', 'fighting'),
  ('Hitmontop', 'fighting'),
  ('Smoochum', 'ice'),
  ('Elekid', 'electric'),
  ('Magby', 'fire'),
  ('Miltank', 'normal'),
  ('Blissey', 'normal'),
  ('Larvitar', 'rock'),
  ('Pupitar', 'rock'),
  ('Tyranitar', 'rock')
) as source(species, attack_type_code)
where target.species = source.species;

insert into public.type_matchups (attack_type_code, defense_type_code, relation)
values
  ('normal', 'normal', 'neutral'),
  ('normal', 'fire', 'neutral'),
  ('normal', 'water', 'neutral'),
  ('normal', 'electric', 'neutral'),
  ('normal', 'grass', 'neutral'),
  ('normal', 'ice', 'neutral'),
  ('normal', 'fighting', 'neutral'),
  ('normal', 'poison', 'neutral'),
  ('normal', 'ground', 'neutral'),
  ('normal', 'flying', 'neutral'),
  ('normal', 'psychic', 'neutral'),
  ('normal', 'bug', 'neutral'),
  ('normal', 'rock', 'resisted'),
  ('normal', 'ghost', 'immune'),
  ('normal', 'dragon', 'neutral'),
  ('normal', 'dark', 'neutral'),
  ('normal', 'steel', 'resisted'),
  ('normal', 'fairy', 'neutral'),
  ('fire', 'normal', 'neutral'),
  ('fire', 'fire', 'resisted'),
  ('fire', 'water', 'resisted'),
  ('fire', 'electric', 'neutral'),
  ('fire', 'grass', 'super_effective'),
  ('fire', 'ice', 'super_effective'),
  ('fire', 'fighting', 'neutral'),
  ('fire', 'poison', 'neutral'),
  ('fire', 'ground', 'neutral'),
  ('fire', 'flying', 'neutral'),
  ('fire', 'psychic', 'neutral'),
  ('fire', 'bug', 'super_effective'),
  ('fire', 'rock', 'resisted'),
  ('fire', 'ghost', 'neutral'),
  ('fire', 'dragon', 'resisted'),
  ('fire', 'dark', 'neutral'),
  ('fire', 'steel', 'super_effective'),
  ('fire', 'fairy', 'neutral'),
  ('water', 'normal', 'neutral'),
  ('water', 'fire', 'super_effective'),
  ('water', 'water', 'resisted'),
  ('water', 'electric', 'neutral'),
  ('water', 'grass', 'resisted'),
  ('water', 'ice', 'neutral'),
  ('water', 'fighting', 'neutral'),
  ('water', 'poison', 'neutral'),
  ('water', 'ground', 'super_effective'),
  ('water', 'flying', 'neutral'),
  ('water', 'psychic', 'neutral'),
  ('water', 'bug', 'neutral'),
  ('water', 'rock', 'super_effective'),
  ('water', 'ghost', 'neutral'),
  ('water', 'dragon', 'resisted'),
  ('water', 'dark', 'neutral'),
  ('water', 'steel', 'neutral'),
  ('water', 'fairy', 'neutral'),
  ('electric', 'normal', 'neutral'),
  ('electric', 'fire', 'neutral'),
  ('electric', 'water', 'super_effective'),
  ('electric', 'electric', 'resisted'),
  ('electric', 'grass', 'resisted'),
  ('electric', 'ice', 'neutral'),
  ('electric', 'fighting', 'neutral'),
  ('electric', 'poison', 'neutral'),
  ('electric', 'ground', 'immune'),
  ('electric', 'flying', 'super_effective'),
  ('electric', 'psychic', 'neutral'),
  ('electric', 'bug', 'neutral'),
  ('electric', 'rock', 'neutral'),
  ('electric', 'ghost', 'neutral'),
  ('electric', 'dragon', 'resisted'),
  ('electric', 'dark', 'neutral'),
  ('electric', 'steel', 'neutral'),
  ('electric', 'fairy', 'neutral'),
  ('grass', 'normal', 'neutral'),
  ('grass', 'fire', 'resisted'),
  ('grass', 'water', 'super_effective'),
  ('grass', 'electric', 'neutral'),
  ('grass', 'grass', 'resisted'),
  ('grass', 'ice', 'neutral'),
  ('grass', 'fighting', 'neutral'),
  ('grass', 'poison', 'resisted'),
  ('grass', 'ground', 'super_effective'),
  ('grass', 'flying', 'resisted'),
  ('grass', 'psychic', 'neutral'),
  ('grass', 'bug', 'resisted'),
  ('grass', 'rock', 'super_effective'),
  ('grass', 'ghost', 'neutral'),
  ('grass', 'dragon', 'resisted'),
  ('grass', 'dark', 'neutral'),
  ('grass', 'steel', 'resisted'),
  ('grass', 'fairy', 'neutral'),
  ('ice', 'normal', 'neutral'),
  ('ice', 'fire', 'resisted'),
  ('ice', 'water', 'resisted'),
  ('ice', 'electric', 'neutral'),
  ('ice', 'grass', 'super_effective'),
  ('ice', 'ice', 'resisted'),
  ('ice', 'fighting', 'neutral'),
  ('ice', 'poison', 'neutral'),
  ('ice', 'ground', 'super_effective'),
  ('ice', 'flying', 'super_effective'),
  ('ice', 'psychic', 'neutral'),
  ('ice', 'bug', 'neutral'),
  ('ice', 'rock', 'neutral'),
  ('ice', 'ghost', 'neutral'),
  ('ice', 'dragon', 'super_effective'),
  ('ice', 'dark', 'neutral'),
  ('ice', 'steel', 'resisted'),
  ('ice', 'fairy', 'neutral'),
  ('fighting', 'normal', 'super_effective'),
  ('fighting', 'fire', 'neutral'),
  ('fighting', 'water', 'neutral'),
  ('fighting', 'electric', 'neutral'),
  ('fighting', 'grass', 'neutral'),
  ('fighting', 'ice', 'super_effective'),
  ('fighting', 'fighting', 'neutral'),
  ('fighting', 'poison', 'resisted'),
  ('fighting', 'ground', 'neutral'),
  ('fighting', 'flying', 'resisted'),
  ('fighting', 'psychic', 'resisted'),
  ('fighting', 'bug', 'resisted'),
  ('fighting', 'rock', 'super_effective'),
  ('fighting', 'ghost', 'immune'),
  ('fighting', 'dragon', 'neutral'),
  ('fighting', 'dark', 'super_effective'),
  ('fighting', 'steel', 'super_effective'),
  ('fighting', 'fairy', 'resisted'),
  ('poison', 'normal', 'neutral'),
  ('poison', 'fire', 'neutral'),
  ('poison', 'water', 'neutral'),
  ('poison', 'electric', 'neutral'),
  ('poison', 'grass', 'super_effective'),
  ('poison', 'ice', 'neutral'),
  ('poison', 'fighting', 'neutral'),
  ('poison', 'poison', 'resisted'),
  ('poison', 'ground', 'resisted'),
  ('poison', 'flying', 'neutral'),
  ('poison', 'psychic', 'neutral'),
  ('poison', 'bug', 'neutral'),
  ('poison', 'rock', 'resisted'),
  ('poison', 'ghost', 'resisted'),
  ('poison', 'dragon', 'neutral'),
  ('poison', 'dark', 'neutral'),
  ('poison', 'steel', 'immune'),
  ('poison', 'fairy', 'super_effective'),
  ('ground', 'normal', 'neutral'),
  ('ground', 'fire', 'super_effective'),
  ('ground', 'water', 'neutral'),
  ('ground', 'electric', 'super_effective'),
  ('ground', 'grass', 'resisted'),
  ('ground', 'ice', 'neutral'),
  ('ground', 'fighting', 'neutral'),
  ('ground', 'poison', 'super_effective'),
  ('ground', 'ground', 'neutral'),
  ('ground', 'flying', 'immune'),
  ('ground', 'psychic', 'neutral'),
  ('ground', 'bug', 'resisted'),
  ('ground', 'rock', 'super_effective'),
  ('ground', 'ghost', 'neutral'),
  ('ground', 'dragon', 'neutral'),
  ('ground', 'dark', 'neutral'),
  ('ground', 'steel', 'super_effective'),
  ('ground', 'fairy', 'neutral'),
  ('flying', 'normal', 'neutral'),
  ('flying', 'fire', 'neutral'),
  ('flying', 'water', 'neutral'),
  ('flying', 'electric', 'resisted'),
  ('flying', 'grass', 'super_effective'),
  ('flying', 'ice', 'neutral'),
  ('flying', 'fighting', 'super_effective'),
  ('flying', 'poison', 'neutral'),
  ('flying', 'ground', 'neutral'),
  ('flying', 'flying', 'neutral'),
  ('flying', 'psychic', 'neutral'),
  ('flying', 'bug', 'super_effective'),
  ('flying', 'rock', 'resisted'),
  ('flying', 'ghost', 'neutral'),
  ('flying', 'dragon', 'neutral'),
  ('flying', 'dark', 'neutral'),
  ('flying', 'steel', 'resisted'),
  ('flying', 'fairy', 'neutral'),
  ('psychic', 'normal', 'neutral'),
  ('psychic', 'fire', 'neutral'),
  ('psychic', 'water', 'neutral'),
  ('psychic', 'electric', 'neutral'),
  ('psychic', 'grass', 'neutral'),
  ('psychic', 'ice', 'neutral'),
  ('psychic', 'fighting', 'super_effective'),
  ('psychic', 'poison', 'super_effective'),
  ('psychic', 'ground', 'neutral'),
  ('psychic', 'flying', 'neutral'),
  ('psychic', 'psychic', 'resisted'),
  ('psychic', 'bug', 'neutral'),
  ('psychic', 'rock', 'neutral'),
  ('psychic', 'ghost', 'neutral'),
  ('psychic', 'dragon', 'neutral'),
  ('psychic', 'dark', 'immune'),
  ('psychic', 'steel', 'resisted'),
  ('psychic', 'fairy', 'neutral'),
  ('bug', 'normal', 'neutral'),
  ('bug', 'fire', 'resisted'),
  ('bug', 'water', 'neutral'),
  ('bug', 'electric', 'neutral'),
  ('bug', 'grass', 'super_effective'),
  ('bug', 'ice', 'neutral'),
  ('bug', 'fighting', 'resisted'),
  ('bug', 'poison', 'resisted'),
  ('bug', 'ground', 'neutral'),
  ('bug', 'flying', 'resisted'),
  ('bug', 'psychic', 'super_effective'),
  ('bug', 'bug', 'neutral'),
  ('bug', 'rock', 'neutral'),
  ('bug', 'ghost', 'resisted'),
  ('bug', 'dragon', 'neutral'),
  ('bug', 'dark', 'super_effective'),
  ('bug', 'steel', 'resisted'),
  ('bug', 'fairy', 'resisted'),
  ('rock', 'normal', 'neutral'),
  ('rock', 'fire', 'super_effective'),
  ('rock', 'water', 'neutral'),
  ('rock', 'electric', 'neutral'),
  ('rock', 'grass', 'neutral'),
  ('rock', 'ice', 'super_effective'),
  ('rock', 'fighting', 'resisted'),
  ('rock', 'poison', 'neutral'),
  ('rock', 'ground', 'resisted'),
  ('rock', 'flying', 'super_effective'),
  ('rock', 'psychic', 'neutral'),
  ('rock', 'bug', 'super_effective'),
  ('rock', 'rock', 'neutral'),
  ('rock', 'ghost', 'neutral'),
  ('rock', 'dragon', 'neutral'),
  ('rock', 'dark', 'neutral'),
  ('rock', 'steel', 'resisted'),
  ('rock', 'fairy', 'neutral'),
  ('ghost', 'normal', 'immune'),
  ('ghost', 'fire', 'neutral'),
  ('ghost', 'water', 'neutral'),
  ('ghost', 'electric', 'neutral'),
  ('ghost', 'grass', 'neutral'),
  ('ghost', 'ice', 'neutral'),
  ('ghost', 'fighting', 'neutral'),
  ('ghost', 'poison', 'neutral'),
  ('ghost', 'ground', 'neutral'),
  ('ghost', 'flying', 'neutral'),
  ('ghost', 'psychic', 'super_effective'),
  ('ghost', 'bug', 'neutral'),
  ('ghost', 'rock', 'neutral'),
  ('ghost', 'ghost', 'super_effective'),
  ('ghost', 'dragon', 'neutral'),
  ('ghost', 'dark', 'resisted'),
  ('ghost', 'steel', 'neutral'),
  ('ghost', 'fairy', 'neutral'),
  ('dragon', 'normal', 'neutral'),
  ('dragon', 'fire', 'neutral'),
  ('dragon', 'water', 'neutral'),
  ('dragon', 'electric', 'neutral'),
  ('dragon', 'grass', 'neutral'),
  ('dragon', 'ice', 'neutral'),
  ('dragon', 'fighting', 'neutral'),
  ('dragon', 'poison', 'neutral'),
  ('dragon', 'ground', 'neutral'),
  ('dragon', 'flying', 'neutral'),
  ('dragon', 'psychic', 'neutral'),
  ('dragon', 'bug', 'neutral'),
  ('dragon', 'rock', 'neutral'),
  ('dragon', 'ghost', 'neutral'),
  ('dragon', 'dragon', 'super_effective'),
  ('dragon', 'dark', 'neutral'),
  ('dragon', 'steel', 'resisted'),
  ('dragon', 'fairy', 'immune'),
  ('dark', 'normal', 'neutral'),
  ('dark', 'fire', 'neutral'),
  ('dark', 'water', 'neutral'),
  ('dark', 'electric', 'neutral'),
  ('dark', 'grass', 'neutral'),
  ('dark', 'ice', 'neutral'),
  ('dark', 'fighting', 'resisted'),
  ('dark', 'poison', 'neutral'),
  ('dark', 'ground', 'neutral'),
  ('dark', 'flying', 'neutral'),
  ('dark', 'psychic', 'super_effective'),
  ('dark', 'bug', 'neutral'),
  ('dark', 'rock', 'neutral'),
  ('dark', 'ghost', 'super_effective'),
  ('dark', 'dragon', 'neutral'),
  ('dark', 'dark', 'resisted'),
  ('dark', 'steel', 'neutral'),
  ('dark', 'fairy', 'resisted'),
  ('steel', 'normal', 'neutral'),
  ('steel', 'fire', 'resisted'),
  ('steel', 'water', 'resisted'),
  ('steel', 'electric', 'resisted'),
  ('steel', 'grass', 'neutral'),
  ('steel', 'ice', 'super_effective'),
  ('steel', 'fighting', 'neutral'),
  ('steel', 'poison', 'neutral'),
  ('steel', 'ground', 'neutral'),
  ('steel', 'flying', 'neutral'),
  ('steel', 'psychic', 'neutral'),
  ('steel', 'bug', 'neutral'),
  ('steel', 'rock', 'super_effective'),
  ('steel', 'ghost', 'neutral'),
  ('steel', 'dragon', 'neutral'),
  ('steel', 'dark', 'neutral'),
  ('steel', 'steel', 'resisted'),
  ('steel', 'fairy', 'super_effective'),
  ('fairy', 'normal', 'neutral'),
  ('fairy', 'fire', 'resisted'),
  ('fairy', 'water', 'neutral'),
  ('fairy', 'electric', 'neutral'),
  ('fairy', 'grass', 'neutral'),
  ('fairy', 'ice', 'neutral'),
  ('fairy', 'fighting', 'super_effective'),
  ('fairy', 'poison', 'resisted'),
  ('fairy', 'ground', 'neutral'),
  ('fairy', 'flying', 'neutral'),
  ('fairy', 'psychic', 'neutral'),
  ('fairy', 'bug', 'neutral'),
  ('fairy', 'rock', 'neutral'),
  ('fairy', 'ghost', 'neutral'),
  ('fairy', 'dragon', 'super_effective'),
  ('fairy', 'dark', 'super_effective'),
  ('fairy', 'steel', 'resisted'),
  ('fairy', 'fairy', 'neutral');

do $$
begin
  if (select count(*) from public.types) <> 18 then
    raise exception 'invalid_type_count';
  end if;

  if (select count(*) from public.community_species) <> 240 then
    raise exception 'invalid_species_count';
  end if;

  if exists (
    select species.species
    from public.community_species as species
    left join public.community_species_types as typing using (species)
    group by species.species
    having count(typing.type_code) not between 1 and 2
  ) then
    raise exception 'invalid_species_type_coverage';
  end if;

  if exists (
    select 1
    from public.community_species
    where attack_type_code is null
  ) then
    raise exception 'missing_attack_type';
  end if;

  if (select count(*) from public.type_matchups) <> 324 then
    raise exception 'invalid_matchup_count';
  end if;
end
$$;

set constraints community_species_attack_type_member_fkey immediate;

alter table public.community_species
  alter column attack_type_code set not null;

comment on column public.community_species.attack_type_code is
  'Type used when the Pokemon attacks without a specific move; guaranteed to be one of the species types.';
